#!/usr/bin/env ruby
# encoding: utf-8

require 'tempfile'

file = ARGV.shift
unless file
    puts("USAGE: #{File.basename __FILE__} FILE")
    exit 0
end

file_dir, file= File.split file

file_theirs = File.join(file_dir, 'tmp.theirs.'+file)
file_ours = File.join(file_dir, 'tmp.ours.'+file)
file = File.join(file_dir, file)

#commonbase = `git show :1:#{file}`             # common base
system "git show :3:#{file} > #{file_theirs}"   # theirs
system "git show :2:#{file} > #{file_ours}"     # ours
#system "cp #{file} #{file}.merged.tmp"              # merged

if `uname`.strip.downcase == 'darwin'
cmd1 = "mvim -c 'set diffopt+=iwhite' -d #{file_theirs} #{file}"
cmd2 = "mvim -c 'set diffopt+=iwhite' -d #{file_ours} #{file}"
cmd3 = "mvim -c 'set diffopt+=iwhite' -d #{file_theirs} #{file_ours}"
else
cmd1 = "vim -c 'set diffopt+=iwhite' -g -d #{file_theirs} #{file}"
cmd2 = "vim -c 'set diffopt+=iwhite' -g -d #{file_ours} #{file}"
cmd3 = "vim -c 'set diffopt+=iwhite' -g -d #{file_theirs} #{file_ours}"
end

puts cmd1
puts cmd2
puts cmd3

system cmd1
system cmd2
system cmd3

# this is readonly, not good
#
cmd = "git difftool :2:#{file} :3:#{file}"
puts "Or run this command(but these files will be readonly):"
puts '> ' + cmd
