#!/usr/bin/env ruby

commit = ARGV.shift
commit_full = `git rev-parse #{commit}`.strip

# print self:
# log = `git log --pretty="%H %ad %an %s" --date=short -1 #{commit}`.strip
# puts "#{log}"

class String
    def first_parent
        `git rev-parse #{self}^1`.strip
    end

    def second_parent
        `git rev-parse #{self}^2`.strip
    end

    def merged_when branch = 'HEAD'
        rv = `git-merged-when #{self} #{branch}`
        if $?.exitstatus == 0
            rv.strip.split(',')[1]
        else
            nil
        end
    end
end

parent = commit.merged_when 'HEAD'

while true
    log = `git log --pretty="%H %ad %an %s" --date=short -1 #{parent}`.strip
    # log = `git lg -1 #{parent}`.strip
    puts "#{log}"
    break if parent == commit_full

    parent2 = commit.merged_when parent
    if parent2 == parent
        # So we're still in the same branch, switch to merged in(i.e. 2nd) branch
        parent = parent.second_parent
    else
        # puts "else else"
        parent = parent2
    end
end
