#!/usr/bin/env ruby
# encoding: utf-8

if ARGV.length < 1
    puts "USAGE: #{File.basename(__FILE__)} SHA1 [SHA2]"
    puts "\nShow files changed between SHA1 and SHA2"
    exit
end
verbose = ARGV.delete('--verbose') || ARGV.delete('-v')
sha1 = ARGV.shift
sha2 = ARGV.shift || ''
# ref:
# http://stackoverflow.com/questions/1552340/git-show-all-changed-files-between-two-commits
cmd = "git diff --name-only #{sha1} #{sha2} | sort | uniq"
puts '> ' + cmd #if verbose
system cmd
